version: '2'

services:
  mariadb:
    container_name: mariadb
    build: ./docker/mariadb
    volumes:
      - ${DB_PATH}:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      DB_PATH: '${DB_PATH}'
    networks:
      - drupal
    restart: always
    
  nginx:
    container_name: nginx
    build: ./docker/nginx
    # Pull directly from Dockerhub
    # image: "your_name/nginx"
  
  php:
    # Pull directly from Dockerhub
    # image: "your_name/php"
    container_name: php
    build: ./docker/php
    
    
    
    
    
    
  drupal:
    # Pull directly from Dockerhub
    image: "ankitjain28/php-nginx-composer:latest"
    # build: ./docker/php-nginx-composer/
    # image: "php-nginx-composer"
    container_name: drupal
    ports:
      - "${APP_PORT}:80"
      - "8028:22"
    environment:
      APP_PORT: '${APP_PORT}'
    volumes:
      # - .:/var/www/html
      - drupal-sync:/var/www/html:nocopy
    links:
      - "drupaldb:mysql"
    networks:
      - drupal
    restart: always

volumes:
  drupal-sync:
    external: true
networks:
  drupal:
